# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Members
    weight: 20
    hasChildren: true
  - parent: Members
    name: Professor
    url: /members/professor/
    weight: 1
  - parent: Members
    name: Students
    url: /members/students/
    weight: 2
  - parent: Members
    name: Alumni
    url: /members/alumni/
    weight: 3
  - name: News
    url: /news/
    weight: 30
  - name: Publications
    url: /publications/
    weight: 40
  - name: Gallery
    url: /gallery/
    weight: 50
  - name: Contact
    url: /contact/
    weight: 60
  - name: Join LaMI
    url: /join/
    weight: 70
